apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: yawwpmvn0-go-gitops
  description: This is GitOps manifest for yawwpmvn0-go   
  links:
    - url: https://www.redhat.com/en/solutions/trusted-software-supply-chain
      title: Trusted Secure Supply Chain 
      icon: dashboard
      type: admin-dashboard
  annotations:    
    argocd/app-name: yawwpmvn0-go
    backstage.io/kubernetes-id: yawwpmvn0-go 
    backstage.io/techdocs-ref: dir:. 
    github.com/project-slug: rhopp-rhtap-testing/yawwpmvn0-go-gitops   
spec:
  type: gitops
  owner: user:guest 
  lifecycle: experimental
  dependsOn:
    - component:yawwpmvn0-go
